version: "3.8"

services:
  postgres-db:
    container_name: "squaresDB"
    image: postgres:18.1
    restart: always
    ports:
      - "6000:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres 
      POSTGRES_DB: squares
    volumes:
      - squaresDBVolume:/var/lib/postgresql
volumes:
  squaresDBVolume:
